name: dataviz                          # Our env was made with --prefix
channels:
  - conda-forge 

dependencies:
  - pandas
  - jupyter
  - rpy2
  - r-essentials
  - holoviews
  - bokeh 
  - selenium # bokeh export svg dependency
  - seaborn
  - python=3.7
  
